apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: k8s-flask-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask-app
spec:
  selector:
    matchLabels:
      app: k8s-flask-app
  template:
    metadata:
      labels:
        app: k8s-flask-app
    spec:
      containers:
      - name: k8s-flask-app
        image: k8s-flask-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000